# Generated by Django 6.0.6 on 2026-06-09 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corplife',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corplife',
            name='date',
            field=models.DateTimeField(help_text='Укажите дату и время проведения мероприятия', verbose_name='Дата проведения'),
        ),
    ]
