# Generated by Django 6.0.6 on 2026-06-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0002_corplife_created_at_alter_corplife_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corplife',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='corplife',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='corplife/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='module_project.corplife', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фото мероприятия',
                'verbose_name_plural': 'Фотографии мероприятия',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
