# Generated by Django 6.0.6 on 2026-06-09 13:02

import galleryfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0003_remove_corplife_gallery_alter_corplife_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corplife',
            name='gallery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='Галерея'),
        ),
    ]
