# Generated by Django 6.0.6 on 2026-06-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0004_corplife_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_project.profile', verbose_name='Автор'),
        ),
    ]
