# Generated by Django 6.0.6 on 2026-06-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0006_alter_workplace_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corplife',
            name='gallery',
        ),
    ]
