# Generated by Django 6.0.6 on 2026-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0007_remove_corplife_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название рабочего места'),
        ),
    ]
