# Generated by Django 6.0.6 on 2026-06-16 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0008_alter_workplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
