# Generated by Django 6.0.6 on 2026-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0009_alter_workplace_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
